Remove `include_str` that causes `cargo publish` to fail
When this line is preset, `cargo publish` fails with the error
error: couldn't read src/../../README.md:
No such file or directory (os error 2)

Signed-off-by: Ryan Beck-Buysse <rbuysse@bitwise.io>